FROM python:3.12-slim
WORKDIR /app

# copy package files
COPY src /app/src
COPY requirements.txt /app/requirements.txt

RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 8001

ENV PYTHONPATH=/app/src
CMD ["uvicorn", "src.tradingui.api:app", "--host", "0.0.0.0", "--port", "8001"]
